name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dockeer Login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      run: Docker build -t azure_vote_app:${{github.run_number}} .
      
    
