name: Docker Image CI

on:
  
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      env:
        required: true
jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1
     
    steps:
    - uses: Omairkhalid95/Reuseable-workflow/.github/workflows/main.yaml@main
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: omair095/azure_vote_app_${{ github.event.inputs.env }}:${{github.run_number}}
       
  deploy:
    runs-on: 
      - self-hosted
      - label-1
    needs: build
    
    steps:
 
    - name: Docker Image Updated in Dev Yaml File
      if: ${{ github.event.inputs.env  == 'dev' }}
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: __
        tokenSuffix: __
        files: '["Kubernetes_dev/kubernetes_dev.yaml"]'
      env:
        DOCKER_REGISTRY: omair095
        IMAGE_NAME: azure_vote_app_${{ github.event.inputs.env }}
        IMAGE_TAG: ${{github.run_number}}

    - name: Docker Image Updated in Prod Yaml File
      if: ${{ github.event.inputs.env  == 'prod' }}
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: __
        tokenSuffix: __
        files: '["Kubernetes/kubernetes.yaml"]'
      env:
        DOCKER_REGISTRY: omair095
        IMAGE_NAME: azure_vote_app_${{ github.event.inputs.env }}
        IMAGE_TAG: ${{github.run_number}}
      
    - name: Azure Connection
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Azure Deployment Dev Env
      if: ${{ github.event.inputs.env  == 'dev' }}
      uses: Azure/k8s-deploy@v4
      with:
        manifests: Kubernetes_dev/kubernetes_dev.yaml
    - name: Azure Deployment Prod Env
      if: ${{ github.event.inputs.env  == 'prod' }}
      uses: Azure/k8s-deploy@v4
      with:
        manifests: Kubernetes/kubernetes.yaml
 
    
